print("Bitwise Operations")
x = int(input("Enter x: "))
y = int(input("Enter y: "))
print("Bitwise AND: x&y = ",(x&y))
print("Bitwise OR : x|y = ",(x|y))
print("Bitwise NOT: ~x = ",(~x))
print("Bitwise XOR: x^y = ",(x^y))
print("Bitwise 'Zero fill left shift': x<<y = ",(x<<y))
print("Bitwise 'Signed right shift'  : x>>y = ",(x>>y))
